### ISSUE TITLE
Cannot Render Title Images --> "Invalid"

### ISSUE THREAD

**Issue by morphological** [mltframework/mlt-scripts#27] opened 2018-07-22 19:10 UTC
Successfully compiled melt and it works fine, except when I try to render kdenlvie title clips, the rendered file just shows a black screen saying "Invalid".

The problem is the "kdenlivetitle" module, which is apparently not enabled by default, but I cannot seem to figure out how to get it working. Any ideas?

```
`Configuring framework:
Configuring modules:
Configuring modules/avformat:
Configuring modules/core:
Configuring modules/decklink:
Configuring modules/feeds:
Configuring modules/frei0r:
Configuring modules/gtk2:
- Libexif found, enabling auto rotate
Configuring modules/jackrack:
Configuring modules/kdenlive:
Configuring modules/lumas:
Configuring modules/ndi:
- NDI SDK not found: disabling
Configuring modules/oldfilm:
Configuring modules/opencv:
- OpenCV >= 3.1.0 NOT found, disabling OpenCV modules
Configuring modules/opengl:
Configuring modules/plus:
- libebur128 found: using external libebur128
Configuring modules/rtaudio:
Configuring modules/sdl:
 - using SDL version 1.2.15
Configuring modules/sdl2:
 - using SDL version 2.0.8
Configuring modules/sox:
Configuring modules/swfdec:
- swfdec not found: disabling
Configuring modules/vmfx:
Configuring modules/xml:
Configuring mlt++:
Configuring swig:
LGPLv2.1 license used; GPL components disabled
`
```

**Comment by morphological** [comment] 2018-07-22 19:36
I am using the latest mlt-master git:
https://github.com/mltframework/mlt.git

I installed all the dependencies available on Ubuntu, and proceeded with ./configure and make && make install

I then tested the resulting melt binary with both the AppImage and stable ppa version of Kdenlive and in both instance I was unable to render title clips, as the output file would simply depict a black screen saying "Invalid".

What could be causing this?
During the configuration of the modules, there was no report of a missing dependency or disabled module, relating to kdenlivetitle or qimage.

**Comment by ddennedy** [comment] 2018-07-22 19:48
> I then tested the resulting melt binary with both the AppImage and stable ppa version of Kdenlive

How? Did you specify the particular melt executable in kdenlive settings? The problem with that approach is the melt is dynamically linked to the MLT libs, and this does not guarantee that you are using the MLT that you built. If you run `ldd /path/to/your/melt`, then you can see which libmlt.so is being used?


I am not sure what the cause of this problem is. You should see a message like "[producer_xml] failed to load producer" in the melt output. As you noted, it is failing to load the kdenlivetitle, but I am not sure why. Maybe there is a broken dependency or incompatible/invalid kdenlivetitle file. Once you get the path of libmlt.so that melt is using above, you can also `ldd <libdir>/mlt/libmltkdenlive.so` to see if all the libraries resolve. Also, when you run melt, it should report modules that fail to load.

Why are you not using the MLT that comes with AppImage or that apt installs when using the ppa? Does render work with those MLT builds?

**Comment by ddennedy** [comment] 2018-07-22 20:36
OK, one way to do that is in a terminal:
```
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
kdenlive (or /path/to/kdenlive or melt depending on what you are doing)
```
That environment variable export is effective only in that terminal window & session.

**Comment by morphological** [comment] 2018-07-22 21:09
There still seem to be some conflicts between libs.
I don't want to waste my time with you, so I will do a fresh install and only install the compiled mlt. Then I'll report back so that I can present clean results to you.

Again, thank you very much for your help and patience, most of all.

**Comment by morphological** [comment] 2018-07-23 12:47
OK, I have done some extensive testing now.
After a fresh install of Kubuntu 18.04 and compiling/installing melt, title clips still appear as "Invalid" after rendering. However, render speeds are absolutely amazing.

To confirm that this is exclusively an issue with the melt that I built, I downloaded Shotcut (portable) and used the melt executable in the Kdenlive environment, but also generated a render script which I ran from the terminal, to be sure.
I am certain that it points to the correct libs, as this melt is launched by a script which first sets all the correct pointers:

```
#!/bin/sh
# Set up environment
# Run this instead of trying to run bin/melt. It runs melt with the correct environment.
CURRENT_DIR=$(readlink -f "$0")
INSTALL_DIR=$(dirname "$CURRENT_DIR")
export LD_LIBRARY_PATH="$INSTALL_DIR/lib":$LD_LIBRARY_PATH
export MLT_REPOSITORY="$INSTALL_DIR/lib/mlt"
export MLT_DATA="$INSTALL_DIR/share/mlt"
export MLT_PROFILES_PATH="$INSTALL_DIR/share/mlt/profiles"
export FREI0R_PATH="$INSTALL_DIR/lib/frei0r-1"
export MLT_MOVIT_PATH="$INSTALL_DIR/share/movit"
export QT_PLUGIN_PATH="$INSTALL_DIR/lib/qt5"
export QML2_IMPORT_PATH="$INSTALL_DIR/lib/qml"
"$INSTALL_DIR/bin/melt" "$@"

```
This version of melt is able to render title clips, but unlike the melt I built, it only uses 1 CPU core (despite specifying 4 threads in the render dialog/kdenlive settings/ and even the render script) subsequently taking much longer to render. (With the kdenlive-multi-render script available on github, I was able to get it to use two cores, though)

Ultimately, I need your assistance in properly compiling melt with all the required modules.
In the OP I posted the output of ./configure before compiling mlt.
NDI SDK, SFWDEC & OpenCV are disabled, as I could not find the dependencies anywhere.
Those modules are unrelated to kdenlive title clips, correct?

Is there maybe something I need to enable while using `"./configure --enable"`
such as for example `./configure --enable-qimage`  ?

After doing some deep google searching, I found that other people's ./configure outputs list much more modules than mine.

I tried both the mlt zip from mltframework and the mlt-master git: 
https://github.com/mltframework/mlt/releases --> version 6.10
https://github.com/mltframework/mlt.git --> version 6.11

What am I missing?

**Comment by bmatherly** [comment] 2018-07-23 14:14
> libmltqt.so might be interesting, as I have read that qimage which relates to title images was renamed to qt.

You will need libmltqt.so because that is where kdenlivetitle lives:
https://github.com/mltframework/mlt/tree/master/src/modules/qt

Make sure your configure scripts includes "--enable-gpl" or qt will be excluded from the build. I can see from your OP that you did not have GPL enabled:

> LGPLv2.1 license used; GPL components disabled

In your configure output, you should see:
`Configuring modules/qt:`

**Comment by morphological** [comment] 2018-07-23 16:07
Thanks for the tip!

I recompiled using `./configure --enable-gpl --enable-gpl3` and two things happened.

Title Clips work properly now, but only 1 CPU core is being used for rendering, quadrupling render times.
I specified 4 Threads in the Kdenlive Environment / 4 Threads in the Render Dialog and even checked if the generated render script says 4 threads, which it does.

With the previous melt all 4 cores were running at 100%, so something about the qt modules must still not be right.

Is there anything else I should --enable with regards to qt or any other related modules that pertain to the issue at hand?

Thanks again for the effort, guys!

**Comment by bmatherly** [comment] 2018-07-23 17:37
> Is there anything else I should --enable with regards to qt or any other related modules that pertain to the issue at hand?

I doubt it. But I don't know anything about the kdenlivetitler. That is maintained by the KDENLIVE developers. It might be better to ask them.

**Comment by morphological** [comment] 2018-07-23 17:41
So --enable-gpl and --enable-gpl3 basically includes a whole bunch of qt modules, right?

If I get 100% CPU usage on all 4 cores without those two ./configure flags and only 1 CPU core with them, then something must be broken with qt or any other modules these two flags enable, wouldn't you agree?

**Comment by ddennedy** [comment] 2018-07-23 18:11
> So --enable-gpl and --enable-gpl3 basically includes a whole bunch of qt modules, right?

No, it enables a few MLT modules, one of which is qt, which houses the kdenlivetitle service.
```
$ find . -name gpl
./src/modules/kino/gpl
./src/modules/linsys/gpl
./src/modules/motion_est/gpl
./src/modules/normalize/gpl
./src/modules/plusgpl/gpl
./src/modules/qt/gpl
./src/modules/resample/gpl
./src/modules/vid.stab/gpl
./src/modules/videostab/gpl
./src/modules/xine/gpl
```

>  If I get 100% CPU usage on all 4 cores without those two ./configure flags and only 1 CPU core with them, then something must be broken with qt or any other modules these two flags enable, wouldn't you agree?

No, parallel processing is a complicated subject. The services in the qt module cannot directly affect the parallelism of other modules such as avformat and the frame-threaded rendering in mlt_consumer.c. Some services are simply heavy or contain locks to prevent parallelism around code that is not thread-safe. These can create bottlenecks. As you noticed, if a service fails to load, then it repeatedly displays INVALID, which is going to process much faster than the real thing. There are not many build-time options that control parallelism, mainly just runtime. You said you checked it, but you did not specify. Mainly dependencies such as ffmpeg, vid.stab, qt, etc. have some compile-time options that affect performance such as enabling assemblers, libgomp, etc. Basically, there are many variables, and it depends - including your project. You can't honestly compare apples to lemons (incomplete build).

**Comment by morphological** [comment] 2018-07-24 09:40
Ok, I have compiled and tested both mlt 6.11 and 6.10 from the mltframework/mlt git, which have yielded the same results as shown below.

For this test I used mlt 6.11, successfully compiled by Dan Dennedy's build-melt.sh

The test file that I am using is the 1080p version of Sintel.
https://durian.blender.org/download/

CPU: i5 6600K, GPU:GTX 750 TI nvidia-390 driver

In order to check melt and isolate the problem I simply rendered the first minute of the Sintel short film with the following command:
(This is not the /bin/melt, but the script which launches it with the correct libs)

`/home/frank/melt/20180724/melt -profile atsc_1080p_60 sintel.mkv out=3600 -consumer avformat:result-60.mp4 f=mp4 vcodec=h264_nvenc preset=slow`
[CPU Utilization: 67% - 70% - 68% - 74%] [Video Engine Utilization (NVENC): 80%] [Render Time: 20s]

It obviously works perfectly.

Now when I select this melt in the kdenlive environment, and also ffmpeg, ffplay, ffprobe and the profiles path from Dan's melt folder, yields the following results when rendering the first minute of Sintel.

**Comment by ddennedy** [comment] 2018-07-25 00:32
kdenlive_multirender talks about threads, but it is really processes. That piece unncessarily complicates the analysis and discussion. So, leave that out. 

I see from your melt command line and the kdenlive render script that you are not using real_time < -1. If you use real_time=-<N> (goes after `-consumer avformat`), then MLT will use N rendering threads. That is the first thing to do to get more CPU usage. Try with -2 or -3. Anything less than -3 might not be as advantageous. Of course, as I explained above, due to concurrency limitations in parts of the code, that is not guaranteed.

Next, Kdenlive uses Qt-based MLT transition qtblend to composite video tracks. If /home/frank/Documents/scripts/script001.sh.mlt has multiple tracks, then it might be in play and thus Qt's image processing. Perhaps your /home/frank/Qt5.11.1 has more optimizations enable by default than the one with your distribution. I know for sure that Qt can be configured at compile-time to disable various SIMD instruction sets to make a theoretically safer binary to execute (it is supposed to use run-time CPU detection to avoid illegal instructions, but maybe some orgs do not trust that enough). I do not know if Qt has support for stuff like OpenML and OpenCL that can be configured in a build to further optimize, but it's possible.

**Comment by morphological** [comment] 2018-07-25 19:47
Alright, I believe that I've figured it out, and shall report back after further testing.
It appears that the root cause of this issue has been **Track Compositing**, all along.

Here are my findings:

Rendering 1st minute of Sintel 1080p/60FPS , 4 Threads, NVENC enabled,  Kdenlive 18.04 AppImage

**.)Track Composition - "None"**
[CPU Utilization: 70% - 67% - 64% - 80%] [GPU Utilization: 70%] [Render Time: 15s]
I noticed however, that transitions such as for example Slide or Composite are rendered improperly, with certain interference patterns.

After consulting the documentation, I realized that this should be fixed by disabling any surrounding empty tracks, but so far I have not been able to achieve that.

**.)Track Composition - "Preview"**
[CPU Utilization: 67% - 65% - 69% - 75%] [GPU Utilization: 65%] [Render Time: 20s]

I conclude that the best of both worlds comes into play with this option enabled.
Both the GPU and CPU are almost fully utilized, while it appears that transitions are rendered correctly.

**.)Track Composition - "High Quality"**
[CPU Utilization: 10% - 14% - 20% - 100%] [GPU Utilization: 6%] [Render Time: 2m58s]

I will do more thorough testing and read any documentation available, as I absolutely want to understand what exactly these options do.

I think it's a bit crazy to have "High Quality" enabled by default, which so heavily impacts performance, while in my opinion not making enough of an effort to alert the user to the extreme effects it may have on render times.

I literally spent 72 hours straight, compiling every single version of melt and kdenlive, documenting and testing every possible compilation parameter variation, performance reviews with every available version of Ubuntu, corresponding kernels and nvidia drivers, and every remotely related kdenlive option or workarounds.

Kdenlive Website:

> High Quality: this uses the new Composite and Transform transition (internally known as qtblend). As this option name suggests, it is giving the best compositing quality, at a slight cost of performance. On a fast machine you might be well able to composite several layers of images (with transparency) onto a video clip and play back the timeline at 25fps.

**Comment by vpinon** [comment] 2018-07-25 20:08
Hello,

Many thanks for your tests, can I let you forward this discussion to kdenlive@kde.org mailing list?
This is the best way to reach kdenlive dev & "qtblend" author (jb) and let other kdenlive users know.
I share your opinion that the default option should be "composite" transition, at least until qtblend gets optimized!

Regards,

Vincent

Le mercredi 25 juillet 2018, 21:47:40 CEST morphological a écrit :

Alright, I believe that I've figured it out, and shall report back after further testing.
It appears that the root cause of this issue has been Track Compositing, all along.
Here are my findings:
Rendering 1st minute of Sintel 1080p/60FPS , 4 Threads, NVENC enabled, Kdenlive 18.04 AppImage
.)Track Composition - "None"
[CPU Utilization: 70% - 67% - 64% - 80%] [GPU Utilization: 70%] [Render Time: 15s]
I noticed however, that transitions such as for example Slide or Composite are rendered improperly, with certain interference patterns.
After consulting the documentation, I realized that this should be fixed by disabling any surrounding empty tracks, but so far I have not been able to achieve that.
.)Track Composition - "Preview"
[CPU Utilization: 67% - 65% - 69% - 75%] [GPU Utilization: 65%] [Render Time: 20s]
I conclude that the best of both worlds comes into play with this option enabled.
Both the GPU and CPU are almost fully utilized, while it appears that transitions are rendered correctly.
.)Track Composition - "High Quality"
[CPU Utilization: 10% - 14% - 20% - 100%] [GPU Utilization: 6%] [Render Time: 2m58s]
I will do more thorough testing and read any documentation available, as I absolutely want to understand what exactly these options do.
I think it's a bit crazy to have "High Quality" enabled by default, which so heavily impacts performance, while in my opinion not making enough of an effort to alert the user to the extreme effects it may have on render times.
I literally spent 72 hours straight, compiling every single version of melt and kdenlive, documenting and testing every possible compilation parameter variation, performance reviews with every available version of Ubuntu, corresponding kernels and nvidia drivers, and every remotely related kdenlive option or workarounds.
Kdenlive Website:
High Quality: this uses the new Composite and Transform transition (internally known as qtblend). As this option name suggests, it is giving the best compositing quality, at a slight cost of performance. On a fast machine you might be well able to composite several layers of images (with transparency) onto a video clip and play back the timeline at 25fps.

**Comment by morphological** [comment] 2018-07-25 22:50
Hey Vincent,

I already submitted my findings to the mailing list before I posted them here.
Check your mail!

I am getting really deep into this now.
By editing the .mlt file that is created with the kdenlive render script to provide instructions, specifically the mlt composite producer and nvenc entries, I am now able to achieve 100% on all 4 cores, but more impressively, 98% of video engine utilization.

Render Times have been reduced to 9-10s.

I should note that I have since then disabled the vid.stab module in mlt 6.11 and switched to nvidia-396, not sure if that is related.

I will post my final test results tomorrow and subsequently close this issue.

Thank you Dan, Vincent and Bmatherly!
I feel very lucky that we have such an active and helpful community with professionals such as yourselves who still take the time to offer their knowledge and support.

Without you this issue would have _melted_ my face by now. (get it?)

**Closed** 2019-12-02 20:07 UTC
